

-- OBTENER LAS INICIALES DE UNA VARAIBLE Y PONERLAS EN MAYUSCULA Y PINTAR EN PANTALLA
-- DIFICULTAD BASICOOOO
SET SERVEROUTPUT ON
DECLARE
nombre varchar2(100) := 'MIGUEL';
APELLIDOUNO varchar2(100) := 'SANCHEZ';
APELLIDODOS varchar2(100) := 'SANCHEZ';
iniciales varchar2(20);
BEGIN

iniciales := UPPER(SUBSTR(nombre, 1, 1)) || '.'||UPPER(SUBSTR(APELLIDOUNO, 1, 1))|| '.'||UPPER(SUBSTR(APELLIDODOS, 1, 1));
DBMS_OUTPUT.PUT_LINE('INICIALES DEL '||nombre|| ' ' || APELLIDOUNO||' '||APELLIDODOS||'-->'|| iniciales);

END;
/


